# Generated by Django 5.2.3 on 2025-06-30 04:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Introduce el nombre completo del curso.', max_length=100, verbose_name='Nombre del Curso')),
                ('descripcion', models.TextField(help_text='Proporciona una descripción completa del contenido del curso.', verbose_name='Descripción detallada')),
                ('imagen', models.ImageField(help_text='Sube una imagen representativa del curso.', upload_to='cursos_imagenes/', verbose_name='Imagen del Curso')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se registró el curso. Se genera automáticamente.', verbose_name='Fecha de Creación')),
                ('duracion_horas', models.PositiveIntegerField(default=0, help_text='Número de horas que dura el curso.', verbose_name='Duración (horas)')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Costo del curso en pesos.', max_digits=10, verbose_name='Precio ($)')),
                ('activo', models.BooleanField(default=True, help_text='Marca si el curso está actualmente disponible.', verbose_name='Activo')),
                ('categoria', models.CharField(choices=[('PROG', 'Programación'), ('BD', 'Bases de Datos'), ('DIS', 'Diseño'), ('MARK', 'Marketing'), ('OTRO', 'Otro')], default='PROG', help_text='Selecciona la categoría a la que pertenece el curso.', max_length=50, verbose_name='Categoría')),
                ('cupo_maximo', models.SmallIntegerField(blank=True, help_text='Número máximo de estudiantes permitidos en el curso.', null=True, verbose_name='Cupo Máximo')),
            ],
            options={
                'verbose_name_plural': 'Cursos',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
