# Generated by Django 5.2.3 on 2025-06-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['fecha_creacion'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(help_text='Proporciona una descripción completa del contenido del curso.', verbose_name='Descripción Detallada'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró el curso. Se genera automáticamente.', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Sube una imagen representativa del curso.', null=True, upload_to='cursos_imagenes/', verbose_name='Imagen del Curso'),
        ),
    ]
