# Generated by Django 5.2.3 on 2025-07-01 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_options_alter_curso_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave de Actividad')),
                ('nombre_actividad', models.CharField(max_length=150, verbose_name='Nombre de la Actividad')),
                ('descripcion_actividad', models.TextField(verbose_name='Descripción Detallada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró el curso. Se genera automáticamente.', verbose_name='Fecha de Creación')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso', verbose_name='Curso Relacionado')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
