# Generated by Django 5.0.6 on 2025-07-16 03:27

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_actividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='descripcion_actividad',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='cupo_maximo',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='duracion_horas',
        ),
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.IntegerField(default=60, verbose_name='Duración (minutos)'),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_final',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='curso',
            name='gratis',
            field=models.BooleanField(default=False, verbose_name='¿Es gratuito?'),
        ),
        migrations.AddField(
            model_name='curso',
            name='maximo',
            field=models.IntegerField(default=0, verbose_name='Cupo máximo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(default='Sin descripción', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Imagen del curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre del curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Precio'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='descripcion_Actividad',
            field=ckeditor.fields.RichTextField(default='Nada', verbose_name='Comentario'),
        ),
    ]
